name: Update Pinned Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch pinned repositories
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"query": "query { user(login: \"ejach\") { pinnedItems(first: 6, types: [REPOSITORY]) { nodes { ... on Repository { name description url languages(first: 1) { nodes { name color } } } } } } }"}' \
            https://api.github.com/graphql)

          echo "$RESPONSE" | jq '.data.user.pinnedItems.nodes' > pinned-repos-temp.json
          cat pinned-repos-temp.json

      - name: Check for changes and update
        run: |
          if [ -f "pinned-repos.json" ]; then
            if ! diff -q pinned-repos.json pinned-repos-temp.json > /dev/null; then
              mv pinned-repos-temp.json pinned-repos.json
              git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git add pinned-repos.json
              git commit -m "Update pinned repositories"
              git push
            else
              echo "No changes detected."
              rm pinned-repos-temp.json
            fi
          else
            mv pinned-repos-temp.json pinned-repos.json
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add pinned-repos.json
            git commit -m "Add pinned repositories"
            git push
          fi
